// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aephswdwsvnutbrfcuzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcGhzd2R3c3ZudXRicmZjdXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MjI0MzksImV4cCI6MjA1NjM5ODQzOX0.ZA5E0HtwwmWGVS9Zk4WNosF8HvUpv85DW5foFFeENSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);